### ISSUE TITLE
Add new locations to the randomization pool

### ISSUE THREAD

**Issue by Rainault** [Rainault/qfg1-randomizer#47]
Eight new locations

**Comment by blueskirt** [comment]
Potential item locations (in case they are not included in your eight new locations):
- Winning the dagger throwing mini game with the maximum possible bet. (I could be wrong but I think the AI is stronger the higher you bet)
- The crumpled piece of paper underneath the bar stool
- Reward for helping the fox
- Reward for defeating a Saurus Rex
- Reward for defeating eight goblins in a row at the goblins training grounds

**Comment by Rainault** [comment]
These are good suggestions! Some of them are indeed on my list of eight.
